[profile.default]
src = "src"
test = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./out" },
    { access = "write", path = "./reports" }
]
solc = "0.8.25"
ffi = true
evm_version = "cancun"
bytecode_hash = "none"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
